# Site settings
title: Aaron C.
description: Aaron's Blahg

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aaroncrespo.com" # the base hostname & protocol for your site

author:
  fullname: Aaron C.
  github: aaroncrespo
  twitter: aaroncrespo
  # disqus: your_disqus_username

google_analytics: 'UA-32863879-1'

# Handling Reading
exclude: ["README.md", "README.html"]

# Plugins
gems:
    - jekyll-minifier

# Build settings
sass:
  style: compressed

highlighter: pygments
markdown: redcarpet
redcarpet:
  syntax_highlighter: rogue
  input: GFM
  enable_coderay: true

