# Site settings
title: Aaron C.
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aaroncrespo.com" # the base hostname & protocol for your site

author:
  fullname: Aaron C.
  github: aaroncrespo
  twitter: aaroncrespo
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
markdown: kramdown
kramdown:
  input: 		  GFM
  enable_coderay: true
