#!/usr/bin/env bash

DIRTY=`(git status -s)`

if [ -n "$DIRTY" ]; then
  echo "Dirty Changes, Failed"
  echo $DIRTY
else
  TEMP= "_temp"
  git push
  git checkout source
  git pull
  jekyll b -d $TEMP

  git checkout gh-pages
  cp -a $TEMP/. .
  rm -r $TEMP
  MESSAGE=`(git log -n1 --pretty="%h - %s" origin/source)`
  MESSAGE="Publishing: $MESSAGE"
  git add .
  git commit -am "$MESSAGE"
  git push
  git checkout -
fi
